# The stocks shown on the site: ticker symbol -> company name.
# Symbols ending in .TO trade on the Toronto Stock Exchange.
# To add a stock, add a line here.

STOCKS = {
    "AAPL": "Apple Inc.",
    "MSFT": "Microsoft Corporation",
    "NVDA": "NVIDIA Corporation",
    "AMZN": "Amazon.com, Inc.",
    "GOOGL": "Alphabet Inc. Class A",
    "META": "Meta Platforms, Inc.",
    "TSLA": "Tesla, Inc.",
    "AVGO": "Broadcom Inc.",
    "AMD": "Advanced Micro Devices, Inc.",
    "INTC": "Intel Corporation",
    "QCOM": "QUALCOMM Incorporated",
    "MU": "Micron Technology, Inc.",
    "NFLX": "Netflix, Inc.",
    "ORCL": "Oracle Corporation",
    "CRM": "Salesforce, Inc.",
    "ADBE": "Adobe Inc.",
    "CSCO": "Cisco Systems, Inc.",
    "IBM": "International Business Machines Corporation",
    "TXN": "Texas Instruments Incorporated",
    "NOW": "ServiceNow, Inc.",
    "PANW": "Palo Alto Networks, Inc.",
    "PLTR": "Palantir Technologies Inc.",
    "SNOW": "Snowflake Inc.",
    "JPM": "JPMorgan Chase & Co.",
    "BAC": "Bank of America Corporation",
    "WFC": "Wells Fargo & Company",
    "C": "Citigroup Inc.",
    "GS": "Goldman Sachs Group, Inc.",
    "MS": "Morgan Stanley",
    "AXP": "American Express Company",
    "BLK": "BlackRock, Inc.",
    "SCHW": "Charles Schwab Corporation",
    "UNH": "UnitedHealth Group Incorporated",
    "LLY": "Eli Lilly and Company",
    "JNJ": "Johnson & Johnson",
    "MRK": "Merck & Co., Inc.",
    "ABBV": "AbbVie Inc.",
    "PFE": "Pfizer Inc.",
    "TMO": "Thermo Fisher Scientific Inc.",
    "DHR": "Danaher Corporation",
    "ISRG": "Intuitive Surgical, Inc.",
    "MDT": "Medtronic plc",
    "XOM": "Exxon Mobil Corporation",
    "CVX": "Chevron Corporation",
    "COP": "ConocoPhillips",
    "SLB": "Schlumberger N.V.",
    "CAT": "Caterpillar Inc.",
    "DE": "Deere & Company",
    "GE": "GE Aerospace",
    "HON": "Honeywell International Inc.",
    "RTX": "RTX Corporation",
    "LMT": "Lockheed Martin Corporation",
    "BA": "Boeing Company",
    "UPS": "United Parcel Service, Inc.",
    "FDX": "FedEx Corporation",
    "WMT": "Walmart Inc.",
    "COST": "Costco Wholesale Corporation",
    "HD": "Home Depot, Inc.",
    "LOW": "Lowe's Companies, Inc.",
    "TGT": "Target Corporation",
    "MCD": "McDonald's Corporation",
    "SBUX": "Starbucks Corporation",
    "NKE": "NIKE, Inc.",
    "DIS": "Walt Disney Company",
    "KO": "Coca-Cola Company",
    "PEP": "PepsiCo, Inc.",
    "PG": "Procter & Gamble Company",
    "VZ": "Verizon Communications Inc.",
    "T": "AT&T Inc.",
    "TMUS": "T-Mobile US, Inc.",
    "CMCSA": "Comcast Corporation",
    "RY.TO": "Royal Bank of Canada",
    "TD.TO": "Toronto-Dominion Bank",
    "BNS.TO": "Bank of Nova Scotia",
    "BMO.TO": "Bank of Montreal",
    "CM.TO": "Canadian Imperial Bank of Commerce",
    "NA.TO": "National Bank of Canada",
    "ENB.TO": "Enbridge Inc.",
    "SU.TO": "Suncor Energy Inc.",
    "CNQ.TO": "Canadian Natural Resources",
    "IMO.TO": "Imperial Oil Limited",
    "CNR.TO": "Canadian National Railway",
    "CP.TO": "Canadian Pacific Kansas City",
    "BCE.TO": "BCE Inc.",
    "T.TO": "TELUS Corporation",
    "ATD.TO": "Alimentation Couche-Tard",
    "SHOP.TO": "Shopify Inc.",
    "TRI.TO": "Thomson Reuters Corporation",
    "BN.TO": "Brookfield Corporation",
    "BAM.TO": "Brookfield Asset Management",
}
